hook.Add('PlayerFinishedLoading', 'octolib.setconvars', function()
	RunConsoleCommand('rope_smooth', '0')
	RunConsoleCommand('Rope_wind_dist', '0')
	RunConsoleCommand('Rope_shake', '0')
	RunConsoleCommand('violence_ablood', '1')
	RunConsoleCommand('mat_queue_mode', '-1')
	RunConsoleCommand('cl_threaded_bone_setup', '1')
	RunConsoleCommand('gmod_mcore_test', '1')
	RunConsoleCommand('cl_threaded_client_leaf_system', '0')
	RunConsoleCommand('r_queued_ropes', '1')
	RunConsoleCommand('r_threaded_client_shadow_manager', '1')
	RunConsoleCommand('r_fastzreject', '-1')
	RunConsoleCommand('Cl_ejectbrass', '0')
	RunConsoleCommand('Muzzleflash_light', '0')
	RunConsoleCommand('cl_wpn_sway_interp', '0')
	RunConsoleCommand('in_usekeyboardsampletime', '0')
end)
