octolib.shared('car-dealer/sh_dealer')

octolib.shared('config/car-dealer')

octolib.server('car-dealer/sv_core')
octolib.server('car-dealer/sv_player')
octolib.server('car-dealer/sv_queue')
octolib.server('car-dealer/sv_hooks')
octolib.server('car-dealer/sv_menu')
octolib.server('car-dealer/sv_colors')
octolib.server('car-dealer/sv_refund')
octolib.server('car-dealer/sv_test')

octolib.client('car-dealer/vgui/menu')
octolib.client('car-dealer/vgui/vehbutton')
octolib.client('car-dealer/vgui/vehlist')
octolib.client('car-dealer/vgui/vehmodel')
octolib.client('car-dealer/vgui/vehviewer')
octolib.client('car-dealer/cl_menu')
octolib.client('car-dealer/cl_colors')
octolib.client('car-dealer/cl_refund')
octolib.client('car-dealer/cl_test')
