-- octoinv.registerMarketCatFromShop('everyday')
-- octoinv.registerMarketCatFromShop('tool')
-- octoinv.registerMarketCatFromShop('build')
-- octoinv.registerMarketCatFromShop('prod')
-- octoinv.registerMarketCatFromShop('dish')
-- octoinv.registerMarketCatFromShop('ings')
-- octoinv.registerMarketCatFromShop('pharm', { nostack = true })
octoinv.registerMarketCatFromShop('parts')
