"EffectList"
{



	"Info"
	{
		"CategoryName" "Portal"
	
		"EffectOptions"
		{
			"Beams"
			"
			Glados_Beam
			Glados_Beam_Static

			portal_1_overlap__
			"

			"Tracers"
			"
			Glados_Beam
			Glados_Beam_Static
			"
		}
	}



"//blood_impact.pcf"  //it's just a worse version of the stock source one
"
blood_impact_green_01
blood_impact_red_01
blood_impact_red_01_chunk
blood_impact_red_01_goop
blood_impact_red_01_smalldroplets
blood_impact_yellow_01
"



"cleansers.pcf"
"
Cleanser_edge_1
Cleanser_edge_2
human_cleanser
human_cleanser_buildup
human_cleanser_buildup_3d
human_cleanser_buildup_3d Version #2
human_cleanser_buildup_floor
human_cleanser_buildup_floor2
human_cleanser_large
portal_cleanser
"



"environment.pcf"
"
elevator_beam
elevator_beam3
elevator_beam_top
elevator_core
elevator_core2
water_mist_1024_512
water_mist_1024_512_b
water_mist_256
water_mist_256_b
water_mist_384_128
water_mist_384_128_b
water_mist_512
water_mist_512_128
water_mist_512_128_b
water_mist_512_b
"



"finale_fx.pcf"
"
finale_arms
finale_finalportal
finale_fx
finale_gasescape1
finale_gasescape_initial
finale_glowburn
finale_glowburn2
finale_sparks
finale_sparks2
"



"//fire_01.pcf"  //conflicts with default source engine fx
"
fire_incinerator_base
fire_incinerator_constant
fire_incinerator_constant_
fire_incinerator_constant_2
fire_incinerator_constant_end01
fire_incinerator_constant_end02
fire_incinerator_constant_smoke
fire_incinerator_door
fire_incinerator_door_heatwaver
fire_incinerator_door_smoke
fire_incinerator_door_smoke_constant
fire_incinerator_heatwaver
fire_incinerator_heatwaver_constant
fire_incinerator_window_constant_flames
fire_incinerator_window_constant_flames2
fire_incinerator_window_occaisional_flames
fire_incinerator_window_warp
fire_large_02
fire_large_02_filler
fire_large_02_fillerb
fire_large_02_warp
fire_large_base
fire_medium_01
fire_medium_01_filler
fire_medium_01_fillerb
fire_medium_01_fillerb Version #2
fire_medium_base
fire_ploom_01
smoke_large_02b
smoke_medium_01
"



"glados.pcf"
"
Glados_Beam
Glados_Beam_Electricity
Glados_Beam_Endpoint
Glados_Beam_Parent_0
Glados_Beam_Parent_1
Glados_Beam_Static
"



"neurotoxins.pcf"
"
neurotoxins_step1
neurotoxins_step1b
neurotoxins_step2
neurotoxins_step3
"



"portal_projectile.pcf"
"
portal_1_badsurface
portal_1_badsurface_
portal_1_badvolume
portal_1_badvolume_
portal_1_cleanser
portal_1_near
portal_1_near_in
portal_1_near_out
portal_1_near_warp
portal_1_nofit
portal_1_nofit_warp
portal_1_overlap
portal_1_overlap__
portal_1_overlap_glow
portal_1_overlap_glow_nomove
portal_1_overlap_oval
portal_1_overlap_warp
portal_1_overlap_warp_fast
portal_1_projectile_3rdperson
portal_1_projectile_ball
portal_1_projectile_ball_3rdperson
portal_1_projectile_fiber
portal_1_projectile_stream
portal_1_projectile_stream_pedestal
portal_1_projectile_trail
portal_1_success
portal_2_badsurface
portal_2_badsurface_
portal_2_badvolume
portal_2_badvolume_
portal_2_cleanser
portal_2_cleanser_old
portal_2_near
portal_2_near_in
portal_2_near_out
portal_2_nofit
portal_2_overlap
portal_2_overlap_
portal_2_projectile_3rdperson
portal_2_projectile_ball
portal_2_projectile_ball_3rdperson
portal_2_projectile_fiber
portal_2_projectile_stream
portal_2_projectile_stream_pedestal
portal_2_projectile_trail
portal_2_success
"



"portalgun.pcf"
"
portal_1_charge
portal_1_charge_flash
portal_1_charge_glow
portal_1_charge_pulse
portal_2_charge
portal_2_charge_flash
portal_2_charge_glow
portal_2_charge_pulse
portalgun_1_cleanser
"



"portals.pcf"
"
portal_1_close
portal_1_close_flash
portal_1_edge
portal_1_particles
Portal_1_vacuum
portal_1_vacuum2
Portal_1_vacuum_
portal_2_close
portal_2_edge
portal_2_particles
portal_2_test
portal_2_vacuum
"



"red_blast.pcf"
"
large_spinning
Red_blast
"



"tubes.pcf"
"
broken_tube_suck
broken_tube_suck_b
"






//This is a CUSTOM .pcf file, repackaged because its file name and effect names conflicted with default Source Engine/Gmod effects.

"fire_01_portal.pcf"
"
fire_incinerator_base
fire_incinerator_constant
fire_incinerator_constant_
fire_incinerator_constant_2
fire_incinerator_constant_end01
fire_incinerator_constant_end02
fire_incinerator_constant_smoke
fire_incinerator_door
fire_incinerator_door_heatwaver
fire_incinerator_door_smoke
fire_incinerator_door_smoke_constant
fire_incinerator_heatwaver
fire_incinerator_heatwaver_constant
fire_incinerator_window_constant_flames
fire_incinerator_window_constant_flames2
fire_incinerator_window_occaisional_flames
fire_incinerator_window_warp
portal_fire_large_02
portal_fire_large_02_filler
portal_fire_large_02_fillerb
portal_fire_large_02_warp
portal_fire_large_base
portal_fire_medium_01
portal_fire_medium_01_filler
portal_fire_medium_01_fillerb
portal_fire_medium_01_fillerb Version #2
portal_fire_medium_base
portal_fire_ploom_01
portal_smoke_large_02b
portal_smoke_medium_01
"
}