ENT.Type = "anim"
ENT.Base = "durgz_base"
ENT.PrintName = "Water"
ENT.Category = "Drugs"
ENT.Nicknames = {0}
ENT.OverdosePhrase = {0}
ENT.Author = "Jesus Christ"
ENT.Spawnable = true
ENT.AdminSpawnable = true 
ENT.Information	 = "Clears the mind" 
