local doll = {
	icon = 'octoteam/icons/bust.png',
	mass = 0.15,
	volume = 0.05,
	model = 'models/props_lab/huladoll.mdl',
}

local trash = {
	-- {chance, {class, amount or data}}
	{500, {'craft_screw2', 5}},
	{500, {'craft_paper', 8}},
	{500, {'craft_bottle', 1}},
	{500, {'craft_screwnut', 3}},
	{500, {'craft_nail', 4}},
	{500, {'craft_plank', 1}},
	{500, {'craft_spring', 3}},
	{500, {'craft_bulb', 2}},
	{500, {'tool_hammer', 1}},
	{500, {'tool_wrench', 1}},
	{250, {'tool_foodcont', 3}},
	{250, {'money', 50}},
	{200, {'craft_chip2', 1}},
	{200, {'money', 100}},
	{160, {'craft_battery', 1}},
	{160, {'craft_cnc', 1}},
	{160, {'food', {
		name = L.trash_food_wrap,
		energy = 25,
		maxenergy = 75,
	}}},
	{160, {'food', {
		name = L.trash_food_donut,
		energy = 20,
		maxenergy = 75,
	}}},
	{160, {'food', {
		name = L.trash_food_sandwich,
		energy = 15,
		maxenergy = 75,
	}}},
	{160, {'food', {
		name = L.trash_food_pizza,
		energy = 20,
		maxenergy = 75,
	}}},
	{160, {'food', {
		name = L.trash_food_pie,
		energy = 15,
		maxenergy = 75,
	}}},

	{135, {'tool_pastrybag', 1}},
	{105, {'tool_scoop', 1}},
	{100, {'tool_coffeepot', 1}},
	{100, {'drug_booze', 1}},
	{100, {'ore_iron', 1}},
	{100, {'tool_craft', 1}},
	{75, {'money', 500}},
	{75, {'craft_ink', 1}},
	{70, {'tool_teapot', 1}},
	{60, {'tool_pan', 1}},
	{50, {'ent_dbg_cigarette', 1}},
	{50, {'ore_steel', 1}},
	{50, {'drug_booze2', 1}},
	{50, {'money', 1000}},
	{45, {'tool_pot', 1}},
	{45, {'tool_shaker', 1}},
	{40, {'tool_oventray', 1}},
	{35, {'bpd_fridge', 1}},
	{30, {'bpd_workbench', 1}},
	{23, {'bpd_machine', 1}},
	{23, {'bpd_stove', 1}},
	{20, {'bpd_refinery', 1}},
	{20, {'radio', 1}},
	{16, {'car_kit', 1}},
	{5, {'money', 10000}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = L.statuette_chelog})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = L.statuette_quillin})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = L.statuette_artis})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = L.statuette_nayzer})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = L.statuette_youlas})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = L.statuette_glitch})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = L.statuette_google})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = L.statuette_queeboy})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = L.statuette_benri})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = L.statuette_direded})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = L.statuette_bellash})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = L.statuette_drinda})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = L.statuette_arthas})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = L.statuette_wayzer})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = L.statuette_hellcom})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = L.statuette_hoffman})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = L.statuette_sighty})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = 'Фигурка Ванички'})}},
	{2, {'souvenir', table.Merge(table.Copy(doll), {name = 'Фигурка Кило'})}},
	{1, {'car_att', {
		name = L.statuette_ermak,
		icon = 'octoteam/icons/bust.png',
		att = 'skull',
		model = 'models/Gibs/HGIBS.mdl',
		desc = L.desc_statuette_ermak,
	}}},
}

for _,v in ipairs(trash) do
	octoinv.registerLoot(v[1], {
		mode = 'trash',
		item = v[2],
	})
end
